version: "3.9"

services:
  mysql:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_SCHEMA}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    networks:
      - app-tier
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: .
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_USER_PASSWORD: ${DB_USER_PASSWORD}
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - mysql
    networks:
      - app-tier
    restart: on-failure
    tty: true

networks:
  app-tier:
    driver: bridge

volumes:
  mysql-data: null
